Change napi_callback to return napi_value instead of void
nodejs/abi-stable-node pull request #196
Opened 2017-03-24 09:23 UTC by boingoing

Change ```napi_callback``` to return ```napi_value``` instead of requiring the callback to manually call ```napi_set_return_value```.

When we invoke the callback, we will check the return value and call ```SetReturnValue``` ourselves. If the callback returns ```NULL```, we don't set the return value in v8 which would have the same effect as previously if the callback didn't call ```napi_set_return_value```. Seems to be a more natural way to handle return values from callbacks. As a consequence, remove ```napi_set_return_value```.

Add a ```napi_value``` to ```napi_property_descriptor``` to support string values which couldn't be passed in the ```utf8name``` parameter or symbols as property names. Class names, however, cannot be symbols so this ```napi_value``` must be a string type in that case.

Remove all of the ```napi_callback_info``` helpers except for ```napi_get_cb_info``` and make all the parameters to ```napi_get_cb_info``` optional except for argc.

Update all the test collateral according to these changes.

2017-03-24 09:24 UTC, boingoing commented
@digitalinfinity @jasongin 

Please take a look, I'll push a further commit to fix lint bugs found via CI.

2017-03-24 09:54 UTC, boingoing commented
Passing CI:
https://ci.nodejs.org/job/node-test-commit-linux-abi/93/

2017-03-24 16:41 UTC, jasongin commented on src/node_api.cc
> +      t->SetClassName(property_name.As<v8::String>());
If the property name is not a string, I think this should just skip setting the name of the function, not return an error.

2017-03-24 16:54 UTC, jasongin commented on src/node_api.cc
> +      t->SetClassName(property_name.As<v8::String>());
Actually I don't think `SetClassName()` should be called at all here. The V8 doc for that API says:

> This is used for printing objects created with the function created from the FunctionTemplate as its constructor. 

What this was intended to do was set the function (class method) name. It's odd that `v8::FunctionTemplate` doesn't have a `SetName()` method, while `v8::Function` does.

2017-03-24 16:55 UTC, jasongin commented on src/node_api.cc
> +      t->SetClassName(property_name.As<v8::String>());
Probably the function will get its name from the property name automatically, so there is no need to set the name separately.

2017-03-24 16:58 UTC, jasongin requested changes
Looks good aside from the one issue about class method names. I do think these are definitely improvements to the API surface. And eliminating `napi_set_return_value` will improve performance a little.

But we should consider whether to hold this until after the node PR lands. Does anyone else have thoughts on that?

2017-03-24 18:33 UTC, boingoing commented
Sounds right. I was also confused about why we were calling SetClassName here. Seems that is for constructors, not methods.


From: Jason Ginchereau<mailto:notifications@github.com>
Sent: Friday, March 24, 2017 9:55 AM
To: nodejs/abi-stable-node<mailto:abi-stable-node@noreply.github.com>
Cc: Taylor Woll<mailto:Taylor.Woll@microsoft.com>; Author<mailto:author@noreply.github.com>
Subject: Re: [nodejs/abi-stable-node] Change napi_callback to return napi_value instead of void (#196)


@jasongin commented on this pull request.

________________________________

In src/node_api.cc<https://github.com/nodejs/abi-stable-node/pull/196#discussion_r107950607>:

> @@ -710,7 +724,11 @@ napi_status napi_define_class(napi_env env,
                                     v8impl::FunctionCallbackWrapper::Invoke,
                                     cbdata,
                                     v8::Signature::New(isolate, tpl));
-      t->SetClassName(property_name);
+
+      // Class name has to be an identifier, though property names can be any
+      // property key. Enforce that class name is a string here.
+      RETURN_STATUS_IF_FALSE(property_name->IsString(), napi_string_expected);
+      t->SetClassName(property_name.As<v8::String>());


Probably the function will get its name from the property name automatically, so there is no need to set the name separately.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/nodejs/abi-stable-node/pull/196#discussion_r107950607>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ABf0MyfTwGpY7JzodVPFaUsNlfj4IiIVks5ro_WDgaJpZM4Mn9LL>.

2017-03-24 18:38 UTC, boingoing commented on src/node_api.cc
> +      t->SetClassName(property_name.As<v8::String>());
Sounds right. I was also confused about why we were calling ```SetClassName()``` here. Seems that is for constructors, not methods.

2017-03-24 18:41 UTC, jasongin commented
> all the parameters to napi_get_cb_info optional except for argc

Why isn't `argc` optional also? Maybe methods which don't expect (or ignore) any parameters shouldn't need to supply that.

2017-03-24 18:42 UTC, boingoing commented
This is a little disruptive, yes, waiting for the PR to land is probably fine. I don't want it to get stale, though, since there are so many invasive changes to the test code. Most of the change is in the test code, which is probably not getting as much attention over in the PR.

2017-03-24 18:44 UTC, boingoing commented
> Why isn't argc optional also? Maybe methods which don't expect (or ignore) any parameters shouldn't need to supply that.

I thought about it but figured it didn't make sense because argc is both an in and an out parameter so it's required if argv is provided. That might be fine, though, to say if argv is provided that argc becomes non-optional.

2017-03-24 18:50 UTC, jasongin commented on src/node_api.cc
> +    if (result) {
Anna just commented on the main PR that node style prefers `if (value != nullptr)`. Also below.

2017-03-24 19:18 UTC, jasongin commented
> argv is provided that argc becomes non-optional

Yes. While updating leveldown code I encountered several places where it would be more convenient to pass nullptr for both argc and argv.

2017-03-25 02:31 UTC, boingoing commented on src/node_api.cc
> +    if (result) {
Saw that and updated uses in this PR.

2017-03-25 03:27 UTC, boingoing commented
Another CI job after rebasing
https://ci.nodejs.org/job/node-test-commit-linux-abi/96/

2017-04-11 01:00 UTC, mhdawson commented
landed in main repo closing.

2017-04-11 01:00 UTC, closed without merging