napi: add napi_env to napi_get_last_error_info()
nodejs/abi-stable-node pull request #211
Opened 2017-03-29 20:30 UTC by gabrielschulhof

This makes it necessary to pass napi_env to napi_get_last_error_info()
thereby ensuring that errors can be tied to the napi_env in the future.

Re https://github.com/nodejs/abi-stable-node/issues/198

2017-03-29 20:59 UTC, boingoing commented on src/node_api.cc
> +  (void)env;
Assume this is to suppress unused formal argument warnings? Suppose what we want is actually to use something like ```CHECK_ARG(env);``` instead. That would require ```napi_get_last_error_info()``` to return ```napi_status```, though...

2017-03-29 21:00 UTC, boingoing approved these changes
Looks fine but should ```napi_get_last_error_info``` return a ```napi_status``` ?

2017-03-29 21:22 UTC, jasongin commented
> should napi_get_last_error_info return a napi_status

I'm leaning toward yes, both for consistency with other APIs and so that it can return an error code if you pass it a null/invalid `env`. The alternative is to indicate an error via a null return value, but I don't like that as much.

2017-03-29 21:22 UTC, jasongin commented
You'll need to rebase and merge after my last change. Sorry.

2017-03-29 21:42 UTC, jasongin requested changes
Waiting for a change to return napi_status, or consensus that it is not needed.

2017-03-29 22:44 UTC, jasongin commented
I rebased and pushed a commit to @gabrielschulhof's branch.

2017-03-29 22:44 UTC, jasongin commented
https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-commit-linux-abi/120/

2017-03-29 23:08 UTC, boingoing approved these changes
👍

2017-03-29 23:10 UTC, merged

2017-03-30 06:55 UTC, gabrielschulhof commented
@jasongin @boingoing thanks for jumping in!