Add doc for N-API Abstract Operations APIs
nodejs/abi-stable-node pull request #216
Opened 2017-04-03 06:11 UTC by digitalinfinity

First cut at API documentation for N-API operations that fall under the "Abstract Operations" section in the ECMA262 spec.

2017-04-03 20:35 UTC, jasongin commented on napi_abstract.md
> +N-API exposes a set of APIs to apply some abstract operations on JavaScript Objects.
JavaScript ~~Objects~~ values

2017-04-03 20:37 UTC, jasongin commented on napi_abstract.md
> +1. Coerce JavaScript objects to fundamental JavaScript types
Coerce JavaScript _values_ to specific value types.
(I don't know what "fundamental" was supposed to mean here.)

2017-04-03 20:41 UTC, jasongin commented on napi_abstract.md
> +However, it has support for detecting External objects, and also defaults to `napi_object`
There is no default to `napi_object`. The default case now returns an error.

2017-04-03 20:43 UTC, jasongin commented on napi_abstract.md
> +3. Check for equality between two JavaScript Objects
~~object~~ value
(many places in this doc)

2017-04-03 20:44 UTC, jasongin requested changes
Not all values are objects. :)

2017-04-04 01:10 UTC, digitalinfinity commented on napi_abstract.md
> +3. Check for equality between two JavaScript Objects
Did a find-replace through the document 😄

2017-04-04 01:10 UTC, digitalinfinity commented on napi_abstract.md
> +However, it has support for detecting External objects, and also defaults to `napi_object`
Fixed

2017-04-04 01:11 UTC, digitalinfinity commented on napi_abstract.md
> +1. Coerce JavaScript objects to fundamental JavaScript types
Reworded

2017-04-04 01:11 UTC, digitalinfinity commented on napi_abstract.md
> +N-API exposes a set of APIs to apply some abstract operations on JavaScript Objects.
Fixed

2017-04-04 01:24 UTC, digitalinfinity commented
Thanks @jasongin - pushed a commit that addresses your feedback

2017-04-04 16:47 UTC, jasongin approved these changes

2017-04-04 20:55 UTC, mhdawson requested changes
Generally looks ok, but we need to adjust the line lengths to be <80 chars.

2017-04-04 20:55 UTC, mhdawson commented on napi_abstract.md
> +Some of these operations are documented under [Section 7](https://tc39.github.io/ecma262/#sec-abstract-operations)
Long line ?

2017-04-04 20:55 UTC, mhdawson commented on napi_abstract.md
> +This N-API API implements the abstract operation ToNumber as defined in [Section 7.1.3](https://tc39.github.io/ecma262/#sec-tonumber)
long line (needs to be less than 80 chars)

2017-04-04 20:55 UTC, mhdawson commented on napi_abstract.md
> +napi_status napi_coerce_to_object(napi_env env, napi_value value, napi_value* result)
long line

2017-04-04 20:55 UTC, mhdawson commented on napi_abstract.md
> +napi_status napi_coerce_to_object(napi_env env, napi_value value, napi_value* result)
Note I only pointed out a few of the long lines, there are others.

2017-04-04 23:12 UTC, digitalinfinity commented
@mhdawson thanks for reviewing- fixed the wrapping, PTAL- thanks!

2017-04-05 00:54 UTC, digitalinfinity commented
Thanks @mhdawson - pushed a commit to address your feedback

2017-04-05 20:16 UTC, gabrielschulhof requested changes
Just a few more nits.

2017-04-05 20:16 UTC, gabrielschulhof commented on napi_abstract.md
> +This API can be re-entrant if getters are defined on the passed in Object.
hyphen between "passed" and "in"

2017-04-05 20:16 UTC, gabrielschulhof commented on napi_abstract.md
> +This N-API API represents behavior similar to invoking `typeof` Operator on
"... invoking *the* &#96;typeof&#96; *o*perator on ..."

2017-04-05 20:16 UTC, gabrielschulhof commented on napi_abstract.md
> +This N-API API represents invoking `instanceof` Operator on the object as
"invoking *the* &#96;instanceof&#96; *o*perator on ..."

2017-04-05 20:16 UTC, gabrielschulhof commented on napi_abstract.md
> +This N-API API represents invoking `IsArray` operation on the object
"... invoking *the* &#96;IsArray&#96; operation ..."

2017-04-05 20:16 UTC, gabrielschulhof commented on napi_abstract.md
> +- `[out] result`: Whether the given object is an N-API representation of
"... is a~~n~~ N-API representation ... "

2017-04-05 20:16 UTC, gabrielschulhof commented on napi_abstract.md
> +node-Buffer
&#96;node::Buffer&#96;

2017-04-05 20:16 UTC, gabrielschulhof commented on napi_abstract.md
> +- `[out] result`: Whether the given `napi_value` represents an TypedArray
"... represents a~~n~~ TypedArray"

2017-04-05 21:35 UTC, digitalinfinity commented on napi_abstract.md
> +- `[out] result`: Whether the given object is an N-API representation of
Isn't an N-API correct? I think its "a NAPI" but "an N-API" - IIRC the article depends on whether the first syllable makes a vowel sound, not whether the first letter is a vowel? But I'm not a native speak so I'll defer to @jasongin's command of the English language 😄

2017-04-05 21:39 UTC, jasongin commented on napi_abstract.md
> +- `[out] result`: Whether the given object is an N-API representation of
@digitalinfinity I agree with your usage, and so does http://english.stackexchange.com/questions/1016/do-you-use-a-or-an-before-acronyms

2017-04-05 21:54 UTC, mhdawson approved these changes
Looks good to me subject to Gabriel's nits.

2017-04-05 22:47 UTC, digitalinfinity commented on napi_abstract.md
> +This API can be re-entrant if getters are defined on the passed in Object.
Fixed

2017-04-05 22:47 UTC, digitalinfinity commented on napi_abstract.md
> +This N-API API represents behavior similar to invoking `typeof` Operator on
Fixed

2017-04-05 22:47 UTC, digitalinfinity commented on napi_abstract.md
> +This N-API API represents invoking `instanceof` Operator on the object as
Fixed

2017-04-05 22:47 UTC, digitalinfinity commented on napi_abstract.md
> +This N-API API represents invoking `IsArray` operation on the object
Fixed

2017-04-05 22:47 UTC, digitalinfinity commented on napi_abstract.md
> +node-Buffer
Fixed

2017-04-05 22:47 UTC, digitalinfinity commented on napi_abstract.md
> +- `[out] result`: Whether the given `napi_value` represents an TypedArray
Fixed

2017-04-05 22:48 UTC, digitalinfinity commented
@gabrielschulhof thanks for the review- pushed a new commit to address the last round of feedback

2017-04-11 20:50 UTC, gabrielschulhof approved these changes
LGTM aside from a few minor issues.

2017-04-11 20:50 UTC, gabrielschulhof commented on napi_abstract.md
> +N-API exposes a set of APIs to apply some abstract operations on JavaScript
"...~~apply~~perform..."

2017-04-11 20:50 UTC, gabrielschulhof commented on napi_abstract.md
> +Objects. Some of these operations are documented under
"...~~Objects~~values."

2017-04-11 20:50 UTC, gabrielschulhof commented on napi_abstract.md
> +3. Check for equality between two JavaScript Objects
"~~Objects~~values"

2017-04-11 20:50 UTC, gabrielschulhof commented on napi_abstract.md
> +This N-API API implements the abstract operation ToNumber as defined in
"~~N-API~~"

2017-04-11 20:50 UTC, gabrielschulhof commented on napi_abstract.md
> +This N-API API implements the abstract operation ToObject as defined in
"~~N-API~~"

2017-04-11 20:50 UTC, gabrielschulhof commented on napi_abstract.md
> +This N-API API implements the abstract operation ToString as defined in
"~~N-API~~"

2017-04-11 20:50 UTC, gabrielschulhof commented on napi_abstract.md
> +This N-API API represents behavior similar to invoking the `typeof` Operator on
"~~N-API~~"

2017-04-11 20:50 UTC, gabrielschulhof commented on napi_abstract.md
> +detecting External value. If `value` has a type that is invalid, an error is
"... detecting *an* External ..."

2017-04-11 20:50 UTC, gabrielschulhof commented on napi_abstract.md
> +This N-API API represents invoking the `instanceof` Operator on the object as
"~~N-API~~"

2017-04-11 20:50 UTC, gabrielschulhof commented on napi_abstract.md
> +This N-API API represents invoking the `IsArray` operation on the object
"~~N-API~~"

2017-04-11 20:50 UTC, gabrielschulhof commented on napi_abstract.md
> +- `[out] result`: Whether the given object is an N-API representation of
Oh, right, it sounds like "enn-ay-pea-eye".

2017-04-11 20:50 UTC, gabrielschulhof commented on napi_abstract.md
> +- `[out] result`: Whether the given object is an N-API representation of
Oooh, but then it's like "... is enn enn-ay-pea-eye representation ..."

Perhaps we should say "Whether the given value holds a `node::Buffer`".

2017-04-11 20:50 UTC, gabrielschulhof commented on napi_abstract.md
> +node::Buffer
backticks please

2017-04-11 20:50 UTC, gabrielschulhof commented on napi_abstract.md
> +- `[out] result`: Whether the given object is an N-API representation of
Actually for the API below this one we have "Whether the given &#96;napi_value&#96; represents an Error object", so let's make this similar: "Whether the given &#96;napi_value&#96; represents a &#96;node::Buffer&#96; object".

2017-04-14 00:38 UTC, digitalinfinity commented on napi_abstract.md
> +N-API exposes a set of APIs to apply some abstract operations on JavaScript
Fixed

2017-04-14 00:38 UTC, digitalinfinity commented on napi_abstract.md
> +Objects. Some of these operations are documented under
Fixed

2017-04-14 00:39 UTC, digitalinfinity commented on napi_abstract.md
> +3. Check for equality between two JavaScript Objects
Fixed

2017-04-14 00:39 UTC, digitalinfinity commented on napi_abstract.md
> +This N-API API implements the abstract operation ToNumber as defined in
Fixed

2017-04-14 00:39 UTC, digitalinfinity commented on napi_abstract.md
> +This N-API API implements the abstract operation ToObject as defined in
Fixed

2017-04-14 00:39 UTC, digitalinfinity commented on napi_abstract.md
> +This N-API API implements the abstract operation ToString as defined in
Fixed

2017-04-14 00:39 UTC, digitalinfinity commented on napi_abstract.md
> +This N-API API represents behavior similar to invoking the `typeof` Operator on
Fixed

2017-04-14 00:39 UTC, digitalinfinity commented on napi_abstract.md
> +detecting External value. If `value` has a type that is invalid, an error is
Fixed

2017-04-14 00:39 UTC, digitalinfinity commented on napi_abstract.md
> +This N-API API represents invoking the `instanceof` Operator on the object as
Fixed

2017-04-14 00:39 UTC, digitalinfinity commented on napi_abstract.md
> +This N-API API represents invoking the `IsArray` operation on the object
Fixed

2017-04-14 00:39 UTC, digitalinfinity commented on napi_abstract.md
> +node::Buffer
Fixed

2017-04-14 00:39 UTC, digitalinfinity commented on napi_abstract.md
> +- `[out] result`: Whether the given object is an N-API representation of
ok- changed

2017-04-14 00:41 UTC, digitalinfinity commented
Thanks @gabrielschulhof - fixed all the nits - I'll leave the PR open for another day in case you want to take another look, but since you've already approved, I'll land this tomorrow if you have no additional feedback

2017-04-18 19:04 UTC, mhdawson commented
landed as 2f8e42d102190cc46672bc297df684bf718ad97f

2017-04-18 19:04 UTC, closed without merging